set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

"Plugin 'Yggdroot/indentLine'
"Plugin 'aradzu10/a.vim'
Plugin 'aradzu10/fzf.vim'
"Plugin 'aradzu10/vim-signify'
Plugin 'bfrg/vim-cpp-modern'
"Plugin 'easymotion/vim-easymotion'
"Plugin 'ervandew/supertab'
"Plugin 'frazrepo/vim-rainbow'
Plugin 'junegunn/fzf'
Plugin 'kshenoy/vim-signature'
"Plugin 'ludovicchabant/vim-gutentags'
"Plugin 'lygaret/autohighlight.vim'
"Plugin 'machakann/vim-highlightedyank'
"Plugin 'majutsushi/tagbar'
Plugin 'morhetz/gruvbox'
Plugin 'preservim/nerdcommenter'
Plugin 'rhysd/clever-f.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
"Plugin 'vim-scripts/h2cppx'
Plugin 'dense-analysis/ale'
Plugin 'prabirshrestha/vim-lsp'
Plugin 'prabirshrestha/asyncomplete.vim'
Plugin 'mattn/vim-lsp-settings'

call vundle#end()            " required
filetype plugin indent on    " required

" Options and keybindings shared with neovim
source ~/.vim/base.vim

" ------------ ALE ------------

let g:ale_fixers = {
\ '*' : ['remove_trailing_lines','trim_whitespace'],
\ 'python' : ['ruff', 'ruff_format'],
\ 'c' : ['clang-tidy', 'clang-format'],
\}
let g:ale_completion_enabled=1

" Search cword and not jump
"noremap * *``

" ------------ Completion & LSP ------------

inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"
inoremap <expr> <C-@> <Plug>(asyncomplete_force_refresh)
au User lsp_setup call lsp#register_server({
    \ 'name': 'jedi-language-server',
    \ 'cmd': {server_info->['pylsp']},
    \ 'allowlist': ['python'],
    \ })

" IdeaVim cannot parse this line:
" exe "source ~/.vim/extrarc.vim"
